import type { Metadata } from "next";
import { fetchBootstrapData } from "./BootstrapData";
import { BootstrapDataClient } from "./BootstrapDataClient";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function BootstrapData({ children }: { children: React.ReactNode }) {
  const bootstrapData = await fetchBootstrapData();
  return (
    <div>
      <div>BootstrapData: {JSON.stringify(bootstrapData)}</div>
      <BootstrapDataClient data={bootstrapData}>{children}</BootstrapDataClient>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BootstrapData>{children}</BootstrapData>
      </body>
    </html>
  );
}
